version: 0.2

phases:
  build:
    commands:
      - echo Build starting on `date`
      - chmod +x ./gradlew
      - ./gradlew -x test build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd

cache:
  paths:
    - '/root/.gradle/caches/**/*'

artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes